server:
  port: 30101

# spring 配置
spring:
  application:
    name: alinesno-infra-base-starter-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_base_starter_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.base.starter.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_base_starter_idx_
  unique:
    prefix: alinesno_base_starter_uni_

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:

# AIP Git 初始化配置信息
alinesno.init.gen:
  # Gitea配置信息
  gitea:
    authurl: "http://git.linesno.com"  # gitea认证路径
    clientId: ""  # gitea OAuth客户端ID
    clientSecrets: ""  # gitea OAuth客户端密钥
    redirectUrl: "http://alinesno-infra-base-starter-boot.beta.base.infra.linesno.com/api/infra/base/starter/bingGit/callback"  # gitea认证回调地址
    userInfo: "http://git.linesno.com/api/v1/user"  # gitea获取用户信息接口

  # Gitee配置信息
  gitee:
    authurl: "https://gitee.com"  # gitee认证路径
    clientId: ""  # gitee OAuth客户端ID
    clientSecrets: ""  # gitee OAuth客户端密钥
    redirectUrl: "http://alinesno-infra-base-starter-boot.beta.base.infra.linesno.com/api/infra/base/starter/bingGit/callback"  # gitea认证回调地址
    userInfo: "https://gitee.com/api/v5/user"  # gitee获取用户信息接口

  # GitHub配置信息
  github:
    authurl: "https://github.com"  # GitHub认证路径
    clientId: ""  # GitHub OAuth客户端ID
    clientSecrets: ""  # GitHub OAuth客户端密钥
    redirectUrl: "http://alinesno-infra-base-starter-boot.beta.base.infra.linesno.com/api/infra/base/starter/bingGit/callback"  # gitea认证回调地址
    userInfo: "https://api.github.com/user"  # GitHub获取用户信息接口
